// real_coaches.js — Coach-level source of truth
// Represents data pulled from Salesforce + Weekly Self-Report
// Pay periods: biweekly starting Jan 25 2026 through May 03 2026
// Ramp definition: isRamping = within 90 days AFTER onboarding (onboarding = first 30 days from hire)

// ─── Pay period IDs in chronological order ───────────────────
// jan25, feb08, feb22, mar08, mar22, apr05, apr19, may03

// Helper: build 8 periods of history for a coach.
// currentData = metrics at may03 (latest).
// growthRate = how fast they were growing (0.6 = started at 60% of current).
// startPeriodIndex = period index when this coach started (0=jan25 … 7=may03).
// For ramping coaches, periods before they started = null.
function buildHistory(id, current, growthRate, startPeriodIndex) {
  const periods = ['jan25','feb08','feb22','mar08','mar22','apr05','apr19','may03'];
  // Deterministic small variance per coach
  const seed = (id * 17 + 31) % 10; // 0-9
  const jitter = (base, i) => {
    const v = ((id * (i+1) * 13) % 7) - 3; // -3 to +3
    return Math.max(0, Math.round(base + v));
  };

  const history = {};
  periods.forEach((ppId, i) => {
    if (i < startPeriodIndex) { history[ppId] = null; return; }
    // Linear interpolation from growthRate*current at startPeriodIndex to current at may03
    const totalPeriods = 7 - startPeriodIndex; // periods from start to now
    const elapsed = i - startPeriodIndex;
    const t = totalPeriods === 0 ? 1 : elapsed / totalPeriods;
    const factor = growthRate + (1 - growthRate) * t;

    history[ppId] = {
      activeClients:      jitter(Math.round(current.activeClients * factor), i),
      recurringClients:   jitter(Math.round(current.recurringClients * factor), i),
      sessionsCompleted:  jitter(Math.round(current.sessionsCompleted * factor), i),
      equifitsCompleted:  jitter(Math.round(current.equifitsCompleted * factor), i),
      equifitsBooked:     jitter(Math.round(current.equifitsBooked * factor), i),
      cptsCompleted:      jitter(Math.round(current.cptsCompleted * factor), i),
      opportunitiesCreated: jitter(Math.round(current.opportunitiesCreated * factor), i),
      conversions:        jitter(Math.round(current.conversions * factor), i),
      leadsGenerated:     jitter(Math.round(current.leadsGenerated * factor), i),
      followUps:          jitter(Math.round(current.followUps * factor), i),
      spu:                parseFloat((current.spu * (0.85 + 0.15 * t)).toFixed(1)),
      sessionConfirmRate: Math.round(current.sessionConfirmRate * (0.88 + 0.12 * t)),
      clientExperience:   current.clientExperience,
      avgProgramFrequency: current.avgProgramFrequency
    };
    // Clamp negatives
    Object.keys(history[ppId]).forEach(k => {
      if (typeof history[ppId][k] === 'number' && history[ppId][k] < 0) history[ppId][k] = 0;
    });
    // Recurring can't exceed active
    if (history[ppId].recurringClients > history[ppId].activeClients) {
      history[ppId].recurringClients = history[ppId].activeClients;
    }
    // Conversions can't exceed opportunities
    if (history[ppId].conversions > history[ppId].opportunitiesCreated) {
      history[ppId].conversions = history[ppId].opportunitiesCreated;
    }
  });
  return history;
}

window.REAL_COACHES = [
  // ─── TOP PERFORMERS ───────────────────────────────────────
  {
    id: 1,
    name: "Jordan Rivera",
    level: "Coach+",
    club: "SoHo",
    isRamping: false,
    rampStage: null,
    isAtRisk: false,
    // Current (may03) snapshot — also used for overview cards
    activeClients: 18,
    recurringClients: 14,
    sessionsCompleted: 56,
    equifitsCompleted: 6,
    equifitsBooked: 5,
    cptsCompleted: 5,
    opportunitiesCreated: 22,
    conversions: 8,
    leadsGenerated: 9,
    followUps: 6,
    spu: 7.2,
    sessionConfirmRate: 91,
    clientExperience: "Excellent",
    avgProgramFrequency: 3,
    history: buildHistory(1,
      {activeClients:18,recurringClients:14,sessionsCompleted:56,equifitsCompleted:6,equifitsBooked:5,cptsCompleted:5,opportunitiesCreated:22,conversions:8,leadsGenerated:9,followUps:6,spu:7.2,sessionConfirmRate:91,clientExperience:"Excellent",avgProgramFrequency:3},
      0.62, 0)
  },
  {
    id: 2,
    name: "Ava Thompson",
    level: "Coach",
    club: "SoHo",
    isRamping: false,
    rampStage: null,
    isAtRisk: false,
    activeClients: 16,
    recurringClients: 13,
    sessionsCompleted: 48,
    equifitsCompleted: 5,
    equifitsBooked: 4,
    cptsCompleted: 4,
    opportunitiesCreated: 18,
    conversions: 7,
    leadsGenerated: 8,
    followUps: 5,
    spu: 6.8,
    sessionConfirmRate: 89,
    clientExperience: "Excellent",
    avgProgramFrequency: 3,
    history: buildHistory(2,
      {activeClients:16,recurringClients:13,sessionsCompleted:48,equifitsCompleted:5,equifitsBooked:4,cptsCompleted:4,opportunitiesCreated:18,conversions:7,leadsGenerated:8,followUps:5,spu:6.8,sessionConfirmRate:89,clientExperience:"Excellent",avgProgramFrequency:3},
      0.65, 0)
  },
  {
    id: 3,
    name: "Marcus Lee",
    level: "Coach+",
    club: "SoHo",
    isRamping: false,
    rampStage: null,
    isAtRisk: false,
    activeClients: 15,
    recurringClients: 12,
    sessionsCompleted: 45,
    equifitsCompleted: 5,
    equifitsBooked: 4,
    cptsCompleted: 4,
    opportunitiesCreated: 16,
    conversions: 6,
    leadsGenerated: 7,
    followUps: 5,
    spu: 6.5,
    sessionConfirmRate: 88,
    clientExperience: "Good",
    avgProgramFrequency: 3,
    history: buildHistory(3,
      {activeClients:15,recurringClients:12,sessionsCompleted:45,equifitsCompleted:5,equifitsBooked:4,cptsCompleted:4,opportunitiesCreated:16,conversions:6,leadsGenerated:7,followUps:5,spu:6.5,sessionConfirmRate:88,clientExperience:"Good",avgProgramFrequency:3},
      0.68, 0)
  },
  {
    id: 4,
    name: "Priya Shah",
    level: "Coach",
    club: "SoHo",
    isRamping: false,
    rampStage: null,
    isAtRisk: false,
    activeClients: 14,
    recurringClients: 11,
    sessionsCompleted: 41,
    equifitsCompleted: 4,
    equifitsBooked: 4,
    cptsCompleted: 3,
    opportunitiesCreated: 15,
    conversions: 5,
    leadsGenerated: 6,
    followUps: 4,
    spu: 6.2,
    sessionConfirmRate: 87,
    clientExperience: "Good",
    avgProgramFrequency: 2,
    history: buildHistory(4,
      {activeClients:14,recurringClients:11,sessionsCompleted:41,equifitsCompleted:4,equifitsBooked:4,cptsCompleted:3,opportunitiesCreated:15,conversions:5,leadsGenerated:6,followUps:4,spu:6.2,sessionConfirmRate:87,clientExperience:"Good",avgProgramFrequency:2},
      0.70, 0)
  },
  {
    id: 5,
    name: "Devon Clarke",
    level: "Coach X",
    club: "SoHo",
    isRamping: false,
    rampStage: null,
    isAtRisk: false,
    activeClients: 20,
    recurringClients: 17,
    sessionsCompleted: 68,
    equifitsCompleted: 7,
    equifitsBooked: 6,
    cptsCompleted: 6,
    opportunitiesCreated: 25,
    conversions: 10,
    leadsGenerated: 11,
    followUps: 8,
    spu: 7.8,
    sessionConfirmRate: 95,
    clientExperience: "Excellent",
    avgProgramFrequency: 3,
    history: buildHistory(5,
      {activeClients:20,recurringClients:17,sessionsCompleted:68,equifitsCompleted:7,equifitsBooked:6,cptsCompleted:6,opportunitiesCreated:25,conversions:10,leadsGenerated:11,followUps:8,spu:7.8,sessionConfirmRate:95,clientExperience:"Excellent",avgProgramFrequency:3},
      0.60, 0)
  },
  {
    id: 6,
    name: "Simone Walsh",
    level: "Coach X",
    club: "SoHo",
    isRamping: false,
    rampStage: null,
    isAtRisk: false,
    activeClients: 19,
    recurringClients: 16,
    sessionsCompleted: 62,
    equifitsCompleted: 6,
    equifitsBooked: 5,
    cptsCompleted: 5,
    opportunitiesCreated: 22,
    conversions: 9,
    leadsGenerated: 10,
    followUps: 7,
    spu: 7.5,
    sessionConfirmRate: 93,
    clientExperience: "Excellent",
    avgProgramFrequency: 3,
    history: buildHistory(6,
      {activeClients:19,recurringClients:16,sessionsCompleted:62,equifitsCompleted:6,equifitsBooked:5,cptsCompleted:5,opportunitiesCreated:22,conversions:9,leadsGenerated:10,followUps:7,spu:7.5,sessionConfirmRate:93,clientExperience:"Excellent",avgProgramFrequency:3},
      0.63, 0)
  },
  {
    id: 7,
    name: "Ryan Torres",
    level: "Coach X",
    club: "SoHo",
    isRamping: false,
    rampStage: null,
    isAtRisk: false,
    activeClients: 18,
    recurringClients: 15,
    sessionsCompleted: 58,
    equifitsCompleted: 6,
    equifitsBooked: 5,
    cptsCompleted: 5,
    opportunitiesCreated: 20,
    conversions: 8,
    leadsGenerated: 9,
    followUps: 7,
    spu: 7.2,
    sessionConfirmRate: 92,
    clientExperience: "Excellent",
    avgProgramFrequency: 3,
    history: buildHistory(7,
      {activeClients:18,recurringClients:15,sessionsCompleted:58,equifitsCompleted:6,equifitsBooked:5,cptsCompleted:5,opportunitiesCreated:20,conversions:8,leadsGenerated:9,followUps:7,spu:7.2,sessionConfirmRate:92,clientExperience:"Excellent",avgProgramFrequency:3},
      0.64, 0)
  },
  {
    id: 8,
    name: "Keisha Monroe",
    level: "Coach+",
    club: "SoHo",
    isRamping: false,
    rampStage: null,
    isAtRisk: false,
    activeClients: 13,
    recurringClients: 10,
    sessionsCompleted: 42,
    equifitsCompleted: 4,
    equifitsBooked: 4,
    cptsCompleted: 4,
    opportunitiesCreated: 14,
    conversions: 5,
    leadsGenerated: 6,
    followUps: 4,
    spu: 6.3,
    sessionConfirmRate: 86,
    clientExperience: "Good",
    avgProgramFrequency: 3,
    history: buildHistory(8,
      {activeClients:13,recurringClients:10,sessionsCompleted:42,equifitsCompleted:4,equifitsBooked:4,cptsCompleted:4,opportunitiesCreated:14,conversions:5,leadsGenerated:6,followUps:4,spu:6.3,sessionConfirmRate:86,clientExperience:"Good",avgProgramFrequency:3},
      0.67, 0)
  },
  // ─── BUILDING ─────────────────────────────────────────────
  {
    id: 9,
    name: "Taylor Williams",
    level: "Coach",
    club: "SoHo",
    isRamping: false,
    rampStage: null,
    isAtRisk: false,
    activeClients: 9,
    recurringClients: 6,
    sessionsCompleted: 24,
    equifitsCompleted: 3,
    equifitsBooked: 2,
    cptsCompleted: 2,
    opportunitiesCreated: 10,
    conversions: 3,
    leadsGenerated: 4,
    followUps: 3,
    spu: 5.8,
    sessionConfirmRate: 82,
    clientExperience: "Good",
    avgProgramFrequency: 2,
    history: buildHistory(9,
      {activeClients:9,recurringClients:6,sessionsCompleted:24,equifitsCompleted:3,equifitsBooked:2,cptsCompleted:2,opportunitiesCreated:10,conversions:3,leadsGenerated:4,followUps:3,spu:5.8,sessionConfirmRate:82,clientExperience:"Good",avgProgramFrequency:2},
      0.55, 2)
  },
  {
    id: 10,
    name: "Chris Nguyen",
    level: "Coach",
    club: "SoHo",
    isRamping: false,
    rampStage: null,
    isAtRisk: false,
    activeClients: 8,
    recurringClients: 5,
    sessionsCompleted: 21,
    equifitsCompleted: 2,
    equifitsBooked: 2,
    cptsCompleted: 2,
    opportunitiesCreated: 9,
    conversions: 3,
    leadsGenerated: 4,
    followUps: 2,
    spu: 5.5,
    sessionConfirmRate: 80,
    clientExperience: "Good",
    avgProgramFrequency: 2,
    history: buildHistory(10,
      {activeClients:8,recurringClients:5,sessionsCompleted:21,equifitsCompleted:2,equifitsBooked:2,cptsCompleted:2,opportunitiesCreated:9,conversions:3,leadsGenerated:4,followUps:2,spu:5.5,sessionConfirmRate:80,clientExperience:"Good",avgProgramFrequency:2},
      0.52, 2)
  },
  {
    id: 11,
    name: "Maya Patel",
    level: "Coach+",
    club: "SoHo",
    isRamping: false,
    rampStage: null,
    isAtRisk: false,
    activeClients: 8,
    recurringClients: 5,
    sessionsCompleted: 20,
    equifitsCompleted: 2,
    equifitsBooked: 2,
    cptsCompleted: 2,
    opportunitiesCreated: 9,
    conversions: 2,
    leadsGenerated: 3,
    followUps: 2,
    spu: 5.4,
    sessionConfirmRate: 79,
    clientExperience: "Good",
    avgProgramFrequency: 2,
    history: buildHistory(11,
      {activeClients:8,recurringClients:5,sessionsCompleted:20,equifitsCompleted:2,equifitsBooked:2,cptsCompleted:2,opportunitiesCreated:9,conversions:2,leadsGenerated:3,followUps:2,spu:5.4,sessionConfirmRate:79,clientExperience:"Good",avgProgramFrequency:2},
      0.50, 2)
  },
  {
    id: 12,
    name: "Ethan Brown",
    level: "Coach",
    club: "SoHo",
    isRamping: false,
    rampStage: null,
    isAtRisk: false,
    activeClients: 7,
    recurringClients: 4,
    sessionsCompleted: 19,
    equifitsCompleted: 2,
    equifitsBooked: 2,
    cptsCompleted: 2,
    opportunitiesCreated: 8,
    conversions: 2,
    leadsGenerated: 3,
    followUps: 2,
    spu: 5.2,
    sessionConfirmRate: 78,
    clientExperience: "Good",
    avgProgramFrequency: 2,
    history: buildHistory(12,
      {activeClients:7,recurringClients:4,sessionsCompleted:19,equifitsCompleted:2,equifitsBooked:2,cptsCompleted:2,opportunitiesCreated:8,conversions:2,leadsGenerated:3,followUps:2,spu:5.2,sessionConfirmRate:78,clientExperience:"Good",avgProgramFrequency:2},
      0.48, 3)
  },
  {
    id: 13,
    name: "Lena Park",
    level: "Coach",
    club: "SoHo",
    isRamping: false,
    rampStage: null,
    isAtRisk: false,
    activeClients: 8,
    recurringClients: 5,
    sessionsCompleted: 22,
    equifitsCompleted: 3,
    equifitsBooked: 2,
    cptsCompleted: 2,
    opportunitiesCreated: 9,
    conversions: 3,
    leadsGenerated: 4,
    followUps: 2,
    spu: 5.6,
    sessionConfirmRate: 81,
    clientExperience: "Good",
    avgProgramFrequency: 2,
    history: buildHistory(13,
      {activeClients:8,recurringClients:5,sessionsCompleted:22,equifitsCompleted:3,equifitsBooked:2,cptsCompleted:2,opportunitiesCreated:9,conversions:3,leadsGenerated:4,followUps:2,spu:5.6,sessionConfirmRate:81,clientExperience:"Good",avgProgramFrequency:2},
      0.54, 2)
  },
  {
    id: 14,
    name: "James Okonkwo",
    level: "Coach+",
    club: "SoHo",
    isRamping: false,
    rampStage: null,
    isAtRisk: false,
    activeClients: 10,
    recurringClients: 6,
    sessionsCompleted: 26,
    equifitsCompleted: 3,
    equifitsBooked: 3,
    cptsCompleted: 2,
    opportunitiesCreated: 11,
    conversions: 3,
    leadsGenerated: 5,
    followUps: 3,
    spu: 5.9,
    sessionConfirmRate: 83,
    clientExperience: "Good",
    avgProgramFrequency: 2,
    history: buildHistory(14,
      {activeClients:10,recurringClients:6,sessionsCompleted:26,equifitsCompleted:3,equifitsBooked:3,cptsCompleted:2,opportunitiesCreated:11,conversions:3,leadsGenerated:5,followUps:3,spu:5.9,sessionConfirmRate:83,clientExperience:"Good",avgProgramFrequency:2},
      0.56, 2)
  },
  {
    id: 15,
    name: "Chloe Bennett",
    level: "Coach",
    club: "SoHo",
    isRamping: false,
    rampStage: null,
    isAtRisk: false,
    activeClients: 7,
    recurringClients: 4,
    sessionsCompleted: 18,
    equifitsCompleted: 2,
    equifitsBooked: 2,
    cptsCompleted: 1,
    opportunitiesCreated: 8,
    conversions: 2,
    leadsGenerated: 3,
    followUps: 2,
    spu: 5.1,
    sessionConfirmRate: 77,
    clientExperience: "Good",
    avgProgramFrequency: 2,
    history: buildHistory(15,
      {activeClients:7,recurringClients:4,sessionsCompleted:18,equifitsCompleted:2,equifitsBooked:2,cptsCompleted:1,opportunitiesCreated:8,conversions:2,leadsGenerated:3,followUps:2,spu:5.1,sessionConfirmRate:77,clientExperience:"Good",avgProgramFrequency:2},
      0.50, 3)
  },
  {
    id: 16,
    name: "Derek Santos",
    level: "Coach",
    club: "SoHo",
    isRamping: false,
    rampStage: null,
    isAtRisk: false,
    activeClients: 9,
    recurringClients: 5,
    sessionsCompleted: 23,
    equifitsCompleted: 3,
    equifitsBooked: 2,
    cptsCompleted: 2,
    opportunitiesCreated: 10,
    conversions: 3,
    leadsGenerated: 4,
    followUps: 3,
    spu: 5.7,
    sessionConfirmRate: 82,
    clientExperience: "Good",
    avgProgramFrequency: 2,
    history: buildHistory(16,
      {activeClients:9,recurringClients:5,sessionsCompleted:23,equifitsCompleted:3,equifitsBooked:2,cptsCompleted:2,opportunitiesCreated:10,conversions:3,leadsGenerated:4,followUps:3,spu:5.7,sessionConfirmRate:82,clientExperience:"Good",avgProgramFrequency:2},
      0.53, 2)
  },
  {
    id: 17,
    name: "Naomi Reyes",
    level: "Coach",
    club: "SoHo",
    isRamping: false,
    rampStage: null,
    isAtRisk: false,
    activeClients: 7,
    recurringClients: 4,
    sessionsCompleted: 19,
    equifitsCompleted: 2,
    equifitsBooked: 2,
    cptsCompleted: 2,
    opportunitiesCreated: 8,
    conversions: 2,
    leadsGenerated: 3,
    followUps: 2,
    spu: 5.3,
    sessionConfirmRate: 79,
    clientExperience: "Good",
    avgProgramFrequency: 2,
    history: buildHistory(17,
      {activeClients:7,recurringClients:4,sessionsCompleted:19,equifitsCompleted:2,equifitsBooked:2,cptsCompleted:2,opportunitiesCreated:8,conversions:2,leadsGenerated:3,followUps:2,spu:5.3,sessionConfirmRate:79,clientExperience:"Good",avgProgramFrequency:2},
      0.51, 3)
  },
  {
    id: 18,
    name: "Omar Diaz",
    level: "Coach+",
    club: "SoHo",
    isRamping: false,
    rampStage: null,
    isAtRisk: false,
    activeClients: 10,
    recurringClients: 6,
    sessionsCompleted: 25,
    equifitsCompleted: 3,
    equifitsBooked: 3,
    cptsCompleted: 2,
    opportunitiesCreated: 11,
    conversions: 3,
    leadsGenerated: 4,
    followUps: 3,
    spu: 5.8,
    sessionConfirmRate: 81,
    clientExperience: "Good",
    avgProgramFrequency: 2,
    history: buildHistory(18,
      {activeClients:10,recurringClients:6,sessionsCompleted:25,equifitsCompleted:3,equifitsBooked:3,cptsCompleted:2,opportunitiesCreated:11,conversions:3,leadsGenerated:4,followUps:3,spu:5.8,sessionConfirmRate:81,clientExperience:"Good",avgProgramFrequency:2},
      0.55, 2)
  },
  // ─── NEEDS ATTENTION ─────────────────────────────────────
  {
    id: 19,
    name: "Brittany Hayes",
    level: "Coach",
    club: "SoHo",
    isRamping: false,
    rampStage: null,
    isAtRisk: true,
    activeClients: 4,
    recurringClients: 2,
    sessionsCompleted: 10,
    equifitsCompleted: 1,
    equifitsBooked: 1,
    cptsCompleted: 1,
    opportunitiesCreated: 5,
    conversions: 1,
    leadsGenerated: 2,
    followUps: 1,
    spu: 4.2,
    sessionConfirmRate: 65,
    clientExperience: "Developing",
    avgProgramFrequency: 2,
    history: buildHistory(19,
      {activeClients:4,recurringClients:2,sessionsCompleted:10,equifitsCompleted:1,equifitsBooked:1,cptsCompleted:1,opportunitiesCreated:5,conversions:1,leadsGenerated:2,followUps:1,spu:4.2,sessionConfirmRate:65,clientExperience:"Developing",avgProgramFrequency:2},
      0.70, 3)
  },
  {
    id: 20,
    name: "Marcus Webb",
    level: "Coach",
    club: "SoHo",
    isRamping: false,
    rampStage: null,
    isAtRisk: true,
    activeClients: 3,
    recurringClients: 1,
    sessionsCompleted: 8,
    equifitsCompleted: 1,
    equifitsBooked: 1,
    cptsCompleted: 1,
    opportunitiesCreated: 4,
    conversions: 1,
    leadsGenerated: 1,
    followUps: 1,
    spu: 3.8,
    sessionConfirmRate: 60,
    clientExperience: "Developing",
    avgProgramFrequency: 2,
    history: buildHistory(20,
      {activeClients:3,recurringClients:1,sessionsCompleted:8,equifitsCompleted:1,equifitsBooked:1,cptsCompleted:1,opportunitiesCreated:4,conversions:1,leadsGenerated:1,followUps:1,spu:3.8,sessionConfirmRate:60,clientExperience:"Developing",avgProgramFrequency:2},
      0.75, 3)
  },
  {
    id: 21,
    name: "Tanya Flores",
    level: "Coach",
    club: "SoHo",
    isRamping: false,
    rampStage: null,
    isAtRisk: true,
    activeClients: 3,
    recurringClients: 1,
    sessionsCompleted: 9,
    equifitsCompleted: 1,
    equifitsBooked: 1,
    cptsCompleted: 0,
    opportunitiesCreated: 4,
    conversions: 1,
    leadsGenerated: 2,
    followUps: 1,
    spu: 4.0,
    sessionConfirmRate: 62,
    clientExperience: "Developing",
    avgProgramFrequency: 2,
    history: buildHistory(21,
      {activeClients:3,recurringClients:1,sessionsCompleted:9,equifitsCompleted:1,equifitsBooked:1,cptsCompleted:0,opportunitiesCreated:4,conversions:1,leadsGenerated:2,followUps:1,spu:4.0,sessionConfirmRate:62,clientExperience:"Developing",avgProgramFrequency:2},
      0.72, 3)
  },
  {
    id: 22,
    name: "Kyle Jensen",
    level: "Coach",
    club: "SoHo",
    isRamping: false,
    rampStage: null,
    isAtRisk: true,
    activeClients: 4,
    recurringClients: 2,
    sessionsCompleted: 11,
    equifitsCompleted: 1,
    equifitsBooked: 1,
    cptsCompleted: 1,
    opportunitiesCreated: 5,
    conversions: 1,
    leadsGenerated: 2,
    followUps: 1,
    spu: 4.5,
    sessionConfirmRate: 67,
    clientExperience: "Developing",
    avgProgramFrequency: 2,
    history: buildHistory(22,
      {activeClients:4,recurringClients:2,sessionsCompleted:11,equifitsCompleted:1,equifitsBooked:1,cptsCompleted:1,opportunitiesCreated:5,conversions:1,leadsGenerated:2,followUps:1,spu:4.5,sessionConfirmRate:67,clientExperience:"Developing",avgProgramFrequency:2},
      0.68, 3)
  },
  {
    id: 23,
    name: "Paula Kim",
    level: "Coach",
    club: "SoHo",
    isRamping: false,
    rampStage: null,
    isAtRisk: true,
    activeClients: 3,
    recurringClients: 1,
    sessionsCompleted: 8,
    equifitsCompleted: 1,
    equifitsBooked: 0,
    cptsCompleted: 1,
    opportunitiesCreated: 4,
    conversions: 1,
    leadsGenerated: 1,
    followUps: 1,
    spu: 3.9,
    sessionConfirmRate: 61,
    clientExperience: "Developing",
    avgProgramFrequency: 1,
    history: buildHistory(23,
      {activeClients:3,recurringClients:1,sessionsCompleted:8,equifitsCompleted:1,equifitsBooked:0,cptsCompleted:1,opportunitiesCreated:4,conversions:1,leadsGenerated:1,followUps:1,spu:3.9,sessionConfirmRate:61,clientExperience:"Developing",avgProgramFrequency:1},
      0.74, 3)
  },
  {
    id: 24,
    name: "Andre Mitchell",
    level: "Coach",
    club: "SoHo",
    isRamping: false,
    rampStage: null,
    isAtRisk: true,
    activeClients: 5,
    recurringClients: 2,
    sessionsCompleted: 12,
    equifitsCompleted: 1,
    equifitsBooked: 1,
    cptsCompleted: 1,
    opportunitiesCreated: 6,
    conversions: 2,
    leadsGenerated: 2,
    followUps: 1,
    spu: 4.6,
    sessionConfirmRate: 68,
    clientExperience: "Developing",
    avgProgramFrequency: 2,
    history: buildHistory(24,
      {activeClients:5,recurringClients:2,sessionsCompleted:12,equifitsCompleted:1,equifitsBooked:1,cptsCompleted:1,opportunitiesCreated:6,conversions:2,leadsGenerated:2,followUps:1,spu:4.6,sessionConfirmRate:68,clientExperience:"Developing",avgProgramFrequency:2},
      0.65, 3)
  },
  {
    id: 25,
    name: "Fatima Hassan",
    level: "Coach",
    club: "SoHo",
    isRamping: false,
    rampStage: null,
    isAtRisk: true,
    activeClients: 4,
    recurringClients: 2,
    sessionsCompleted: 10,
    equifitsCompleted: 1,
    equifitsBooked: 1,
    cptsCompleted: 1,
    opportunitiesCreated: 5,
    conversions: 1,
    leadsGenerated: 2,
    followUps: 1,
    spu: 4.3,
    sessionConfirmRate: 64,
    clientExperience: "Developing",
    avgProgramFrequency: 2,
    history: buildHistory(25,
      {activeClients:4,recurringClients:2,sessionsCompleted:10,equifitsCompleted:1,equifitsBooked:1,cptsCompleted:1,opportunitiesCreated:5,conversions:1,leadsGenerated:2,followUps:1,spu:4.3,sessionConfirmRate:64,clientExperience:"Developing",avgProgramFrequency:2},
      0.70, 3)
  },
  // ─── RAMPING COACHES ──────────────────────────────────────
  // Ramping = isRamping:true, rampStage set
  // They only have history from when they started ramping
  {
    id: 26,
    name: "Alex Lopez",
    level: "Coach",
    club: "SoHo",
    isRamping: true,
    rampStage: "Month 3",
    rampDay: 80,
    isAtRisk: false,
    activeClients: 7,
    recurringClients: 5,
    sessionsCompleted: 18,
    equifitsCompleted: 3,
    equifitsBooked: 2,
    cptsCompleted: 2,
    opportunitiesCreated: 8,
    conversions: 2,
    leadsGenerated: 3,
    followUps: 2,
    spu: 5.2,
    sessionConfirmRate: 80,
    clientExperience: "Good",
    avgProgramFrequency: 2,
    history: buildHistory(26,
      {activeClients:7,recurringClients:5,sessionsCompleted:18,equifitsCompleted:3,equifitsBooked:2,cptsCompleted:2,opportunitiesCreated:8,conversions:2,leadsGenerated:3,followUps:2,spu:5.2,sessionConfirmRate:80,clientExperience:"Good",avgProgramFrequency:2},
      0.30, 3)
  },
  {
    id: 27,
    name: "Sophie Ramirez",
    level: "Coach+",
    club: "SoHo",
    isRamping: true,
    rampStage: "Month 3",
    rampDay: 77,
    isAtRisk: false,
    activeClients: 6,
    recurringClients: 4,
    sessionsCompleted: 15,
    equifitsCompleted: 3,
    equifitsBooked: 2,
    cptsCompleted: 2,
    opportunitiesCreated: 7,
    conversions: 2,
    leadsGenerated: 3,
    followUps: 2,
    spu: 5.0,
    sessionConfirmRate: 78,
    clientExperience: "Good",
    avgProgramFrequency: 2,
    history: buildHistory(27,
      {activeClients:6,recurringClients:4,sessionsCompleted:15,equifitsCompleted:3,equifitsBooked:2,cptsCompleted:2,opportunitiesCreated:7,conversions:2,leadsGenerated:3,followUps:2,spu:5.0,sessionConfirmRate:78,clientExperience:"Good",avgProgramFrequency:2},
      0.30, 3)
  },
  {
    id: 28,
    name: "Dante Cruz",
    level: "Coach",
    club: "SoHo",
    isRamping: true,
    rampStage: "Month 2",
    rampDay: 48,
    isAtRisk: false,
    activeClients: 4,
    recurringClients: 2,
    sessionsCompleted: 11,
    equifitsCompleted: 2,
    equifitsBooked: 2,
    cptsCompleted: 1,
    opportunitiesCreated: 6,
    conversions: 2,
    leadsGenerated: 3,
    followUps: 2,
    spu: 4.8,
    sessionConfirmRate: 75,
    clientExperience: "Developing",
    avgProgramFrequency: 2,
    history: buildHistory(28,
      {activeClients:4,recurringClients:2,sessionsCompleted:11,equifitsCompleted:2,equifitsBooked:2,cptsCompleted:1,opportunitiesCreated:6,conversions:2,leadsGenerated:3,followUps:2,spu:4.8,sessionConfirmRate:75,clientExperience:"Developing",avgProgramFrequency:2},
      0.25, 5)
  },
  {
    id: 29,
    name: "Mia Sanchez",
    level: "Coach",
    club: "SoHo",
    isRamping: true,
    rampStage: "Month 2",
    rampDay: 35,
    isAtRisk: false,
    activeClients: 3,
    recurringClients: 1,
    sessionsCompleted: 8,
    equifitsCompleted: 2,
    equifitsBooked: 1,
    cptsCompleted: 1,
    opportunitiesCreated: 5,
    conversions: 1,
    leadsGenerated: 2,
    followUps: 1,
    spu: 4.5,
    sessionConfirmRate: 72,
    clientExperience: "Developing",
    avgProgramFrequency: 2,
    history: buildHistory(29,
      {activeClients:3,recurringClients:1,sessionsCompleted:8,equifitsCompleted:2,equifitsBooked:1,cptsCompleted:1,opportunitiesCreated:5,conversions:1,leadsGenerated:2,followUps:1,spu:4.5,sessionConfirmRate:72,clientExperience:"Developing",avgProgramFrequency:2},
      0.20, 6)
  },
  {
    id: 30,
    name: "Zoe Nakamura",
    level: "Coach",
    club: "SoHo",
    isRamping: true,
    rampStage: "Week 4",
    rampDay: 26,
    isAtRisk: false,
    activeClients: 2,
    recurringClients: 1,
    sessionsCompleted: 5,
    equifitsCompleted: 2,
    equifitsBooked: 2,
    cptsCompleted: 1,
    opportunitiesCreated: 3,
    conversions: 1,
    leadsGenerated: 2,
    followUps: 1,
    spu: 4.2,
    sessionConfirmRate: 70,
    clientExperience: "Developing",
    avgProgramFrequency: 2,
    history: buildHistory(30,
      {activeClients:2,recurringClients:1,sessionsCompleted:5,equifitsCompleted:2,equifitsBooked:2,cptsCompleted:1,opportunitiesCreated:3,conversions:1,leadsGenerated:2,followUps:1,spu:4.2,sessionConfirmRate:70,clientExperience:"Developing",avgProgramFrequency:2},
      0.20, 6)
  },
  {
    id: 31,
    name: "Ivan Petrov",
    level: "Coach",
    club: "SoHo",
    isRamping: true,
    rampStage: "Week 4",
    rampDay: 24,
    isAtRisk: false,
    activeClients: 1,
    recurringClients: 1,
    sessionsCompleted: 4,
    equifitsCompleted: 2,
    equifitsBooked: 1,
    cptsCompleted: 0,
    opportunitiesCreated: 3,
    conversions: 1,
    leadsGenerated: 2,
    followUps: 1,
    spu: 4.0,
    sessionConfirmRate: 68,
    clientExperience: "Developing",
    avgProgramFrequency: 1,
    history: buildHistory(31,
      {activeClients:1,recurringClients:1,sessionsCompleted:4,equifitsCompleted:2,equifitsBooked:1,cptsCompleted:0,opportunitiesCreated:3,conversions:1,leadsGenerated:2,followUps:1,spu:4.0,sessionConfirmRate:68,clientExperience:"Developing",avgProgramFrequency:1},
      0.20, 6)
  },
  {
    id: 32,
    name: "Lila Grant",
    level: "Coach",
    club: "SoHo",
    isRamping: true,
    rampStage: "Week 3",
    rampDay: 19,
    isAtRisk: false,
    activeClients: 1,
    recurringClients: 0,
    sessionsCompleted: 3,
    equifitsCompleted: 2,
    equifitsBooked: 2,
    cptsCompleted: 0,
    opportunitiesCreated: 2,
    conversions: 0,
    leadsGenerated: 2,
    followUps: 0,
    spu: 3.5,
    sessionConfirmRate: 65,
    clientExperience: "Developing",
    avgProgramFrequency: 1,
    history: buildHistory(32,
      {activeClients:1,recurringClients:0,sessionsCompleted:3,equifitsCompleted:2,equifitsBooked:2,cptsCompleted:0,opportunitiesCreated:2,conversions:0,leadsGenerated:2,followUps:0,spu:3.5,sessionConfirmRate:65,clientExperience:"Developing",avgProgramFrequency:1},
      0.10, 7)
  },
  {
    id: 33,
    name: "Carlos Vega",
    level: "Coach",
    club: "SoHo",
    isRamping: true,
    rampStage: "Week 3",
    rampDay: 17,
    isAtRisk: false,
    activeClients: 1,
    recurringClients: 0,
    sessionsCompleted: 2,
    equifitsCompleted: 1,
    equifitsBooked: 1,
    cptsCompleted: 0,
    opportunitiesCreated: 2,
    conversions: 0,
    leadsGenerated: 2,
    followUps: 0,
    spu: 3.2,
    sessionConfirmRate: 63,
    clientExperience: "Developing",
    avgProgramFrequency: 1,
    history: buildHistory(33,
      {activeClients:1,recurringClients:0,sessionsCompleted:2,equifitsCompleted:1,equifitsBooked:1,cptsCompleted:0,opportunitiesCreated:2,conversions:0,leadsGenerated:2,followUps:0,spu:3.2,sessionConfirmRate:63,clientExperience:"Developing",avgProgramFrequency:1},
      0.10, 7)
  },
  {
    id: 34,
    name: "Nina Foster",
    level: "Coach",
    club: "SoHo",
    isRamping: true,
    rampStage: "Week 3",
    rampDay: 17,
    isAtRisk: false,
    activeClients: 1,
    recurringClients: 0,
    sessionsCompleted: 2,
    equifitsCompleted: 1,
    equifitsBooked: 1,
    cptsCompleted: 0,
    opportunitiesCreated: 2,
    conversions: 0,
    leadsGenerated: 1,
    followUps: 0,
    spu: 3.0,
    sessionConfirmRate: 62,
    clientExperience: "Developing",
    avgProgramFrequency: 1,
    history: buildHistory(34,
      {activeClients:1,recurringClients:0,sessionsCompleted:2,equifitsCompleted:1,equifitsBooked:1,cptsCompleted:0,opportunitiesCreated:2,conversions:0,leadsGenerated:1,followUps:0,spu:3.0,sessionConfirmRate:62,clientExperience:"Developing",avgProgramFrequency:1},
      0.10, 7)
  },
  {
    id: 35,
    name: "Bryce Hall",
    level: "Coach",
    club: "SoHo",
    isRamping: true,
    rampStage: "Week 2",
    rampDay: 12,
    isAtRisk: false,
    activeClients: 0,
    recurringClients: 0,
    sessionsCompleted: 1,
    equifitsCompleted: 2,
    equifitsBooked: 2,
    cptsCompleted: 0,
    opportunitiesCreated: 1,
    conversions: 0,
    leadsGenerated: 2,
    followUps: 0,
    spu: 2.5,
    sessionConfirmRate: 60,
    clientExperience: "Developing",
    avgProgramFrequency: 1,
    history: buildHistory(35,
      {activeClients:0,recurringClients:0,sessionsCompleted:1,equifitsCompleted:2,equifitsBooked:2,cptsCompleted:0,opportunitiesCreated:1,conversions:0,leadsGenerated:2,followUps:0,spu:2.5,sessionConfirmRate:60,clientExperience:"Developing",avgProgramFrequency:1},
      0.05, 7)
  },
  {
    id: 36,
    name: "Aisha Coleman",
    level: "Coach",
    club: "SoHo",
    isRamping: true,
    rampStage: "Week 2",
    rampDay: 10,
    isAtRisk: false,
    activeClients: 0,
    recurringClients: 0,
    sessionsCompleted: 1,
    equifitsCompleted: 1,
    equifitsBooked: 1,
    cptsCompleted: 0,
    opportunitiesCreated: 1,
    conversions: 0,
    leadsGenerated: 1,
    followUps: 0,
    spu: 2.2,
    sessionConfirmRate: 58,
    clientExperience: "Developing",
    avgProgramFrequency: 1,
    history: buildHistory(36,
      {activeClients:0,recurringClients:0,sessionsCompleted:1,equifitsCompleted:1,equifitsBooked:1,cptsCompleted:0,opportunitiesCreated:1,conversions:0,leadsGenerated:1,followUps:0,spu:2.2,sessionConfirmRate:58,clientExperience:"Developing",avgProgramFrequency:1},
      0.05, 7)
  },
  {
    id: 37,
    name: "Tommy Barrett",
    level: "Coach",
    club: "SoHo",
    isRamping: true,
    rampStage: "Week 1",
    rampDay: 5,
    isAtRisk: false,
    activeClients: 0,
    recurringClients: 0,
    sessionsCompleted: 0,
    equifitsCompleted: 1,
    equifitsBooked: 1,
    cptsCompleted: 0,
    opportunitiesCreated: 0,
    conversions: 0,
    leadsGenerated: 1,
    followUps: 0,
    spu: 0,
    sessionConfirmRate: 0,
    clientExperience: "N/A",
    avgProgramFrequency: 0,
    history: buildHistory(37,
      {activeClients:0,recurringClients:0,sessionsCompleted:0,equifitsCompleted:1,equifitsBooked:1,cptsCompleted:0,opportunitiesCreated:0,conversions:0,leadsGenerated:1,followUps:0,spu:0,sessionConfirmRate:0,clientExperience:"N/A",avgProgramFrequency:0},
      0.0, 7)
  }
];

window.PAY_PERIODS = [
  { id: "jan25", label: "Jan 25", startDate: "2026-01-25" },
  { id: "feb08", label: "Feb 08", startDate: "2026-02-08" },
  { id: "feb22", label: "Feb 22", startDate: "2026-02-22" },
  { id: "mar08", label: "Mar 08", startDate: "2026-03-08" },
  { id: "mar22", label: "Mar 22", startDate: "2026-03-22" },
  { id: "apr05", label: "Apr 05", startDate: "2026-04-05" },
  { id: "apr19", label: "Apr 19", startDate: "2026-04-19" },
  { id: "may03", label: "May 03", startDate: "2026-05-03", isCurrent: true }
];

window.SESSION_RATE_TIERS = [
  { min: 0,  max: 34,       rate: 40.50, label: "0–34"  },
  { min: 35, max: 39,       rate: 46.00, label: "35–39" },
  { min: 40, max: 44,       rate: 61.50, label: "40–44" },
  { min: 45, max: 54,       rate: 65.00, label: "45–54" },
  { min: 55, max: 64,       rate: 69.00, label: "55–64" },
  { min: 65, max: Infinity, rate: 72.50, label: "65+"   }
];

window.EQUIFIT_RATE = 25;
window.CPT_RATE     = 30;
